version: "{build}"
clone_depth: 1
image: Visual Studio 2019 Preview

build_script:
- cmd: call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\VC\\Auxiliary\\Build\\vcvars64.bat"
- cmd: angelscript_windows.bat
- cmd: curl_windows.bat
- cmd: freetype_windows.bat
- cmd: openal_windows.bat
- cmd: sdl_windows.bat
- cmd: zlib_windows.bat
- cmd: zstd_windows.bat

artifacts:
- path: build
  name: libs_windows
